name: scheduler

on:

  push:
    branches:
      - main

  schedule:
    - cron: "*/10 6-17 * * 1-5" # Runs production build every 10 minutes, between 7:00 and 18:59 CET, Monday to Friday.
    - cron: "0 18-23,0-5 * * 1-5" # Runs production build every hour, between 19:00 and 6:59 CET, Monday to Friday.
    - cron: "0 11,17 * * 6,0" # Runs production and staging builds at 12:00 and 18:00 CET, on Saturday and Sunday.
    - cron: "0 11,17 * * 0-6" # Runs staging builds at 12:00 and 18:00 CET, every day.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        environment: [production, staging]
        exclude:
          - environment: production
            ${{ github.event_name == 'schedule' && github.event.schedule.cron == '0 11,17 * * 0-6' }}: true
          - environment: staging
            ${{ github.event_name == 'schedule' && github.event.schedule.cron != '0 11,17 * * 0-6' }}: true

    steps:
      - uses: actions/checkout@v4

      - name: Current time
        run: echo "Scheduler executed at $(date +"%T")"
