name: scheduler

on:
  schedule:
    - cron: "*/5 6-14 * * 1-5" # Runs every 10 minutes, between from 7:00 to 19:00 CET, Monday to Friday.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        environment: [production, staging]

    steps:
      - uses: actions/checkout@v4

      - name: Current time
        run: echo "Scheduler executed at $(date +"%T")"
