name: scheduler

on: 
  push:
    branches: main
  schedule:
    - cron: "*/1 6-18 * * 1-5" # Runs Monday to Friday every 10 minutes from 7:00 to 19:00.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        environment: [production, staging]

    steps:
      - uses: actions/checkout@v4

      - name: Current time
        run: echo "Scheduler executed at $(date +"%T")"
